# Generated by Django 4.2.8 on 2024-01-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100)),
                ('repoName', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(verbose_name='commit timestamp')),
                ('commitMessage', models.TextField()),
                ('commitUrl', models.CharField(max_length=300)),
                ('addedFiles', models.TextField()),
                ('modifiedFiles', models.TextField()),
                ('deletedFiles', models.TextField()),
            ],
        ),
    ]
