# Generated by Django 4.2.8 on 2024-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(max_length=100)),
                ('actions', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
