# Generated by Django 4.2.8 on 2024-01-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0002_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='test timestamp')),
                ('duration', models.FloatField()),
                ('errors', models.IntegerField()),
            ],
        ),
    ]
