# Generated by Django 4.2.8 on 2024-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='hash',
            field=models.CharField(default='dsad', max_length=40),
            preserve_default=False,
        ),
    ]
