# Generated by Django 4.2.8 on 2024-03-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0004_commit_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='GitChecker.repository'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitChecker.repository')),
            ],
        ),
    ]
