# Generated by Django 4.2.8 on 2024-03-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0005_test_repository_testparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GitChecker.repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitChecker.commit'),
        ),
    ]
