# Generated by Django 4.2.8 on 2024-03-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0006_commit_repository_alter_test_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='repository',
            new_name='commit',
        ),
    ]
