# Generated by Django 4.2.8 on 2024-03-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0007_rename_repository_test_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repoId',
            field=models.IntegerField(default=737740662),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GitChecker.repository'),
        ),
        migrations.AlterField(
            model_name='test',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GitChecker.commit'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GitChecker.repository'),
        ),
    ]
