# Generated by Django 4.2.8 on 2024-03-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0008_repository_repoid_alter_commit_repository_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repoId',
            field=models.BigIntegerField(),
        ),
    ]
