# Generated by Django 4.2.8 on 2024-03-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0009_alter_repository_repoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='GitChecker.repository'),
            preserve_default=False,
        ),
    ]
