# Generated by Django 4.2.8 on 2024-03-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0010_test_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='test',
            name='errors',
        ),
        migrations.AddField(
            model_name='test',
            name='detailed',
            field=models.TextField(default={'id': 'lol'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='params',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='GitChecker.testparameters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='summary',
            field=models.TextField(default={'id': 'lol'}),
            preserve_default=False,
        ),
    ]
