# Generated by Django 4.2.8 on 2024-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0011_remove_test_duration_remove_test_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='param_template',
            field=models.JSONField(default='{"key": "value"}'),
        ),
    ]
