# Generated by Django 4.2.8 on 2024-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0013_alter_repository_param_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='test_dir',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='addedFiles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commit',
            name='deletedFiles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commit',
            name='modifiedFiles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='test',
            name='detailed',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='test',
            name='summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
    ]
