# Generated by Django 4.2.8 on 2024-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0014_repository_test_dir_alter_commit_addedfiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='test_command',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
