# Generated by Django 4.2.8 on 2024-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0015_repository_test_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='param_template',
        ),
        migrations.AddField(
            model_name='testparameters',
            name='param_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
