# Generated by Django 4.2.8 on 2024-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0016_remove_repository_param_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameters',
            name='version',
            field=models.CharField(default='python3.10', max_length=16),
        ),
    ]
