# Generated by Django 4.2.8 on 2024-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0017_testparameters_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameters',
            name='parameters',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
