# Generated by Django 4.2.8 on 2024-03-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0018_alter_testparameters_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameters',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
