# Generated by Django 4.2.8 on 2024-03-31 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0019_alter_testparameters_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitChecker.repository'),
        ),
        migrations.AlterField(
            model_name='test',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitChecker.commit'),
        ),
        migrations.AlterField(
            model_name='test',
            name='params',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GitChecker.testparameters'),
        ),
        migrations.AlterField(
            model_name='test',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitChecker.repository'),
        ),
        migrations.AlterField(
            model_name='testparameters',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitChecker.repository'),
        ),
    ]
