# Generated by Django 4.2.8 on 2024-04-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitChecker', '0020_alter_commit_repository_alter_test_commit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='addedFiles',
            new_name='added_files',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='authorName',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='commitMessage',
            new_name='commit_message',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='commitUrl',
            new_name='commit_url',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='deletedFiles',
            new_name='deleted_files',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='modifiedFiles',
            new_name='modified_files',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='repoId',
            new_name='repo_id',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='repoName',
            new_name='repo_name',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='repoName',
        ),
    ]
